import { useEffect, useRef, useState } from "react";
import { DEFAULT_RAMP, rasterizeFallback, type AsciiCell } from "./fallback";

const COLS = 80;
const ROWS = 40;

// The wasm-ascii pkg/ directory only exists after `make build` runs in
// wasm-ascii/ (wasm-pack emits it into frontend/src/ascii/pkg/). On a
// fresh checkout this dynamic import 404s and we silently fall back to
// the TS path below -- documented in root README.
async function loadWasmRasterize(): Promise<
  | ((
      pixels: Uint8Array,
      width: number,
      height: number,
      cols: number,
      rows: number,
      ramp: string,
    ) => Uint8Array)
  | null
> {
  if (typeof WebAssembly === "undefined") return null;
  try {
    // @ts-expect-error -- pkg/ is generated by wasm-pack, not committed.
    const mod = await import("./pkg/wasm_ascii.js");
    await mod.default();
    return mod.rasterize;
  } catch {
    return null;
  }
}

function generateNoiseFrame(width: number, height: number): Uint8ClampedArray {
  const buf = new Uint8ClampedArray(width * height * 4);
  for (let i = 0; i < buf.length; i += 4) {
    const v = Math.floor(Math.random() * 255);
    buf[i] = v;
    buf[i + 1] = v;
    buf[i + 2] = v;
    buf[i + 3] = 255;
  }
  return buf;
}

export function AsciiCanvas({ className }: { className?: string }) {
  const [grid, setGrid] = useState<AsciiCell[][]>([]);
  const rasterizeRef = useRef<Awaited<ReturnType<typeof loadWasmRasterize>>>(null);

  useEffect(() => {
    let cancelled = false;
    loadWasmRasterize().then((fn) => {
      if (!cancelled) rasterizeRef.current = fn;
    });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    const width = 160;
    const height = 80;
    const frame = generateNoiseFrame(width, height);

    if (rasterizeRef.current) {
      // TODO(logan): decode the packed (char_code, brightness) Uint8Array
      // the WASM module returns into AsciiCell[][] once wasm-ascii is built.
      setGrid(rasterizeFallback(frame, width, height, COLS, ROWS, DEFAULT_RAMP));
    } else {
      setGrid(rasterizeFallback(frame, width, height, COLS, ROWS, DEFAULT_RAMP));
    }
  }, []);

  return (
    <pre className={className} aria-hidden="true">
      {grid.map((row) => row.map((cell) => cell.char).join("")).join("\n")}
    </pre>
  );
}
