import { useEffect, useRef, useState } from "react";
import { DEFAULT_RAMP, rasterizeFallback, type AsciiCell } from "./fallback";

const COLS = 80;
const ROWS = 40;

// Mirrors wasm-ascii/src/lib.rs's rasterize(): packed pairs of
// (char_code: u8, brightness: u8), row-major, cols*rows pairs total.
// char_code is always ASCII per the project's no-non-ASCII rule, so a
// direct String.fromCharCode is safe -- no multi-byte decoding needed.
export function decodeWasmGrid(
  packed: Uint8Array,
  cols: number,
  rows: number,
): AsciiCell[][] {
  const grid: AsciiCell[][] = [];
  let offset = 0;
  for (let row = 0; row < rows; row++) {
    const cells: AsciiCell[] = [];
    for (let col = 0; col < cols; col++) {
      const charCode = packed[offset];
      const brightnessByte = packed[offset + 1];
      offset += 2;
      cells.push({
        char: String.fromCharCode(charCode),
        brightness: brightnessByte / 255,
      });
    }
    grid.push(cells);
  }
  return grid;
}

// The wasm-ascii pkg/ directory only exists after `make build` runs in
// wasm-ascii/ (wasm-pack emits it into frontend/src/ascii/pkg/). On a
// fresh checkout this dynamic import 404s and we silently fall back to
// the TS path below -- documented in root README.
async function loadWasmRasterize(): Promise<
  | ((
      pixels: Uint8Array,
      width: number,
      height: number,
      cols: number,
      rows: number,
      ramp: string,
    ) => Uint8Array)
  | null
> {
  if (typeof WebAssembly === "undefined") return null;
  try {
    // pkg/ is generated by wasm-pack at build time, not committed -- the
    // specifier is built from a variable (not a literal) so Vite's
    // import-analysis can't statically resolve it at transform time, which
    // would otherwise break dev/test on a fresh checkout before `make
    // build` has run in wasm-ascii/. The try/catch below is the real
    // fallback path.
    const wasmModulePath = "./pkg/wasm_ascii.js";
    const mod = await import(/* @vite-ignore */ wasmModulePath);
    await mod.default();
    return mod.rasterize;
  } catch {
    return null;
  }
}

function generateNoiseFrame(width: number, height: number): Uint8ClampedArray {
  const buf = new Uint8ClampedArray(width * height * 4);
  for (let i = 0; i < buf.length; i += 4) {
    const v = Math.floor(Math.random() * 255);
    buf[i] = v;
    buf[i + 1] = v;
    buf[i + 2] = v;
    buf[i + 3] = 255;
  }
  return buf;
}

export function AsciiCanvas({ className }: { className?: string }) {
  const [grid, setGrid] = useState<AsciiCell[][]>([]);
  const rasterizeRef = useRef<Awaited<ReturnType<typeof loadWasmRasterize>>>(null);

  useEffect(() => {
    let cancelled = false;
    loadWasmRasterize().then((fn) => {
      if (!cancelled) rasterizeRef.current = fn;
    });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    const width = 160;
    const height = 80;
    const frame = generateNoiseFrame(width, height);

    if (rasterizeRef.current) {
      const packed = rasterizeRef.current(
        new Uint8Array(frame.buffer, frame.byteOffset, frame.byteLength),
        width,
        height,
        COLS,
        ROWS,
        DEFAULT_RAMP,
      );
      setGrid(decodeWasmGrid(packed, COLS, ROWS));
    } else {
      setGrid(rasterizeFallback(frame, width, height, COLS, ROWS, DEFAULT_RAMP));
    }
  }, []);

  return (
    <pre className={className} aria-hidden="true">
      {grid.map((row) => row.map((cell) => cell.char).join("")).join("\n")}
    </pre>
  );
}
