// GENERATED by scripts/generate_ascii_ramp.py -- do not hand-edit.
// Re-run the script and commit this file if the candidate glyph sets
// in that script change.

export const GENERATED_RAMP: string = " `.'-_:;~!>+|LTtIZeXUG#&RQBMN$W@";

// Indexed by an 8-way bucket across a half-turn (0 = horizontal,
// going toward vertical and back) -- matching shapes.ts's
// silhouetteChar(). Ordinary text glyphs, picked by fitting a line
// through each glyph's own outer-edge ink (farthest from its mass
// center, not all of it equally) and matching that line's
// orientation to the bucket's boundary direction.
export const CONTOUR_GLYPHS_TEXT: string[] = ["_", "_", "\\", "\\", "|", "/", "/", "_"];

// Same idea, restricted to Unicode half/quadrant block glyphs --
// reserved for the sphere/globe shape specifically (see shapes.ts).
export const CONTOUR_GLYPHS_BLOCK: string[] = ["\u2580", "\u259d", "\u2590", "\u2597", "\u2584", "\u2596", "\u258c", "\u2598"];
