// GENERATED by scripts/generate_ascii_ramp.py -- do not hand-edit.
// Re-run the script and commit this file if the candidate glyph sets
// in that script change.

export const GENERATED_RAMP: string = " `-,:\";!*r(|izJYIoaXd&#8BM▒▌▓█";

// Indexed by an 8-way compass bucket (0 = up/north, going clockwise),
// matching the bucketing in shapes.ts's silhouetteChar().
export const CONTOUR_GLYPHS: string[] = ["\u2580", "\u259d", "\u2590", "\u2597", "\u2584", "\u2596", "\u258c", "\u2598"];
