// Default brightness ramp, darkest -> brightest. GENERATED by
// scripts/generate_ascii_ramp.py from measured glyph ink coverage --
// kept in sync with frontend/src/ascii/generatedGlyphs.ts's
// GENERATED_RAMP by re-running that script, not by hand.
pub const DEFAULT_RAMP: &str = " `.'-_:;~!>+|LTtIZeXUG#&RQBMN$W@";

pub fn char_for_brightness(brightness: f32, ramp: &str) -> char {
    let ramp = if ramp.is_empty() { DEFAULT_RAMP } else { ramp };
    let chars: Vec<char> = ramp.chars().collect();
    let clamped = brightness.clamp(0.0, 1.0);
    let index = ((clamped * (chars.len() - 1) as f32).floor() as usize).min(chars.len() - 1);
    chars[index]
}
